image: node:16.1.0

cache:
  paths:
    - node_modules/

stages:
  - lint
  - tests
  - coverage

services:
  - name: trufflesuite/ganache-cli
    alias: ganache
    entrypoint: ["node", "/app/ganache-core.docker.cli.js"]

before_script:
  - yarn
  - yarn compile

contracts-lint:
  stage: lint
  script:
    - yarn lint

contracts-tests:
  stage: tests
  script:
    - yarn test --network hardhat

contracts-coverage:
  stage: coverage
  script:
    - yarn coverage --network hardhat
  allow_failure: true
